name: wihotspot
version: "1.0.0-dev"
summary: wihotspot
description: |
  Create wifi hotspot like in windows

confinement: devmode
grade: stable

apps:
  wihotspot:
    command: wihotspot
    plugs: [home, x11, gsettings]

parts:
  wihotspot:
    plugin: make
    build-packages:
      - g++
      - gcc
      - make
      - cmake
      - libgtk-3-dev
      - pkg-config
    stage-packages:
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libpango1.0-0
      - libglib2.0-0
      - libatk1.0-0